### ISSUE TITLE
TODO! Typescript implementation

### ISSUE THREAD

**Issue by KFlash** [buntis/buntis#10]
**This is what to implement:**

- [x] Interface

- [x] Enum

- [x] Type annotations

- [x] Abstract

- [x] Global

- [x] Type

- [x] Const and const enum

- [x] Class

- [x] Functions

- [x] Arrows

- [x] Alias

- [x] Type arguments

- [x] Async functions and async arrows

- [x] Export and import

- [ ] Decorators

- [x] Namespace

- [x] Make sure 100% parity with ESTree

**Comment by KFlash** [comment]
Be aware that the Typescript features that hasn't been implemented yet is kind of super hard to implement without lookaheads, and the may goal with this project is to avoid lookaheads so it may take a while to implement it. But they are all WIP.

**Comment by KFlash** [comment]
The remaining typescript syntax to implement will take awhile to fix because it's **very difficult** to implement this without lookaheads.

I also discovered a few bugs in the Typescript parser itself that I need to handle, plus it seems to be some design flaws in that parser - cases that can't be solved because of how TS have been designed.

Some of the flaws have been adopted by the Babel parser and the @typescript-eslint/parser. One example is this case `<a>b`. Parse it with and without `JSX enabled`.

**Comment by KFlash** [comment]
Closing this now as done. Decorators has to be implmented, but that\s another issue.
The parser now also parses the same tests as found on the TypeScript repo.
